//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheoDoiVanBan
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CongViec
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_CongViec()
        {
            this.tbl_AccountSupport = new HashSet<tbl_AccountSupport>();
        }
    
        public int Id_CongViec { get; set; }
        public Nullable<int> Id_AccountKhoiTao { get; set; }
        public Nullable<int> Id_AccountGiaoViec { get; set; }
        public string SoVanBan { get; set; }
        public Nullable<System.DateTime> NgayPhatHanh { get; set; }
        public string SoGhiSoCongVan { get; set; }
        public Nullable<System.DateTime> NgayNhanVanBan { get; set; }
        public Nullable<int> Id_CoQuanBanHanh { get; set; }
        public Nullable<int> Id_loaiVanBan { get; set; }
        public Nullable<int> Id_LinhVucVanBan { get; set; }
        public string CommentLanhDao { get; set; }
        public string NoiDungVanBan { get; set; }
        public Nullable<System.DateTime> NgayChiDao { get; set; }
        public Nullable<System.DateTime> NgayPhaiHoanThanh { get; set; }
        public Nullable<bool> PhaiBaoCao { get; set; }
        public string NguoiNhanVanBan { get; set; }
        public string TomTatKetQua { get; set; }
        public string TaiLieuDinhKem { get; set; }
        public Nullable<bool> HoanThanh { get; set; }
        public Nullable<bool> ChuaHoanThanh { get; set; }
        public Nullable<bool> DangThucHien { get; set; }
        public Nullable<bool> ChuaThucHien { get; set; }
        public Nullable<bool> ThucHienCham { get; set; }
        public Nullable<bool> KetThucCongViec { get; set; }
        public Nullable<System.DateTime> NgayHoanThanh { get; set; }
        public Nullable<System.DateTime> NgayTaoCongViec { get; set; }
        public Nullable<System.DateTime> NgaySuaCongViec { get; set; }
        public Nullable<bool> StatusForward { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_AccountSupport> tbl_AccountSupport { get; set; }
    }
}
