//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheoDoiVanBan
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_AccountSupport
    {
        public int Id_tbl_AccountSupport { get; set; }
        public Nullable<int> Id_tbl_CongViec { get; set; }
        public Nullable<int> Id_AccountTiepNhan { get; set; }
        public Nullable<System.DateTime> NgayChuyenDen { get; set; }
        public Nullable<System.DateTime> NgayTiepNhan { get; set; }
        public Nullable<System.DateTime> NgayHoanThanhSupport { get; set; }
        public string KetQuaCongViec { get; set; }
        public string PhanCongCongViec { get; set; }
        public Nullable<System.DateTime> NgaySua { get; set; }
        public Nullable<bool> StatusReceived { get; set; }
        public Nullable<bool> StatusFinish { get; set; }
    
        public virtual tbl_Account tbl_Account { get; set; }
        public virtual tbl_CongViec tbl_CongViec { get; set; }
    }
}
